name: Python CI

on:
  push:
    branches: [ "sdat2" ]
  pull_request:
    branches: [ "sdat2" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Conda environment
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-${{ matrix.python-version }}-

    - name: Setup Conda Environment with Mamba üêç
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: env.yml
        auto-update-conda: true
        use-mamba: true # Use the fast Mamba solver

    - name: Run Tests with Pytest
      # Use a conda-aware shell to run in the activated environment
      shell: bash -l {0}
      run: |
        pytest -W ignore::DeprecationWarning